[project]
name = "timestamp-query"
version = "1.1.1"
description = ""
authors = [{ name = "Alan", email = "alan.so@sky.uk" }]
requires-python = ">=3.13,<4"
readme = "README.md"
dependencies = ["plutus"]

[project.scripts]
tq = "timestamp_query.tq:command_line_runner"

[dependency-groups]
dev = ["pytest>=7.4.0,<8", "pytest-cov>=4.1.0,<5", "pytest-mock>=3.11.1,<4"]

[tool.uv]

[tool.uv.sources]
plutus = { path = "../plutus/", editable = true }

[tool.hatch.build.targets.sdist]
include = ["timestamp_query"]

[tool.hatch.build.targets.wheel]
include = ["timestamp_query"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.pyright]
exclude = [
  "**/site-packages/**",
  ".vscode/*.py",
  "**/.venv/**",
  "**/.tox/**",
  "**/build/**",
  "*.coveragerc",
]
